/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.minicomputador.view;

import br.com.minicomputador.model.MemoriaCache;
import br.com.minicomputador.model.MiniComputador;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme Lourenço
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    MiniComputador pc;
    String vetorInstrucoes[];
    
    public TelaPrincipal() {
        initComponents();
        this.taTelaSaida.setBackground(Color.BLACK);
        this.taTelaSaida.setForeground(Color.GREEN);
        this.pc = new MiniComputador(this.taTelaSaida);
        atualizaRegistradores();
        
        //listMemoriaCache2.setListData(vetorCacheLinha);

    }

    public void atualizaRegistradores() {
        txtPC.setText(pc.getProcessador().getPC());
        txtIR.setText(pc.getProcessador().getIR());
        txtMAR.setText(pc.getProcessador().getMAR());
        txtMBR.setText(pc.getProcessador().getMBR());
        txtRegA.setText(pc.getProcessador().getRegistradorA());
        txtRegB.setText(pc.getProcessador().getRegistradorB());
        txtRegC.setText(pc.getProcessador().getRegistradorC());
        txtRegD.setText(pc.getProcessador().getRegistradorD());
        
        //listMemoriaCache.setListData(pc.getMemoriaCache().getLinhasMapeamentoDireto().values().iterator().next().values().toArray());
        ArrayList<String> linha0 = pc.getMemoriaCache().getLinhasMapeamentoDireto().get("0").get("0");
        ArrayList<String> linha1 = pc.getMemoriaCache().getLinhasMapeamentoDireto().get("1").get("1");
        ArrayList<String> linha2 = pc.getMemoriaCache().getLinhasMapeamentoDireto().get("2").get("2");
        ArrayList<String> linha3 = pc.getMemoriaCache().getLinhasMapeamentoDireto().get("3").get("3");
        if(linha0 != null){
            txtLinha1.setText(linha0.toString());
        }
        if(linha1 != null){
            txtLinha2.setText(linha1.toString());
        }
        if(linha2 != null){
            txtLinha3.setText(linha2.toString());
        }
        if(linha3 != null){
            txtLinha4.setText(linha3.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMemoriaPrincipalEnderecos = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMemoriaPrincipal = new javax.swing.JList();
        painel2 = new javax.swing.JPanel();
        txtLinha1 = new javax.swing.JTextField();
        txtLinha2 = new javax.swing.JTextField();
        txtLinha3 = new javax.swing.JTextField();
        txtLinha4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLinha5 = new javax.swing.JTextField();
        txtLinha6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnCacheDireto = new javax.swing.JButton();
        btnCacheAssociativo = new javax.swing.JButton();
        btnCacheConjuntos = new javax.swing.JButton();
        painel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        painel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRegA = new javax.swing.JTextField();
        txtRegB = new javax.swing.JTextField();
        txtRegC = new javax.swing.JTextField();
        txtRegD = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtIR = new javax.swing.JTextField();
        txtMAR = new javax.swing.JTextField();
        txtMBR = new javax.swing.JTextField();
        painel5 = new javax.swing.JPanel();
        painel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtOperando1 = new javax.swing.JTextField();
        txtOperando2 = new javax.swing.JTextField();
        cbOperacao = new javax.swing.JComboBox();
        btnConfirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taPalavras = new javax.swing.JTextArea();
        btnEnviarDados = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnDecodifica = new javax.swing.JButton();
        btnExecuta = new javax.swing.JButton();
        painel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taTelaSaida = new javax.swing.JTextArea();
        btnRestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memória Principal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jScrollPane1.setViewportView(listMemoriaPrincipalEnderecos);

        jScrollPane4.setViewportView(listMemoriaPrincipal);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane4)
        );

        painel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memória Cache", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtLinha1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLinha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtLinha2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLinha2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtLinha3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLinha3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtLinha4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLinha4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Linha 0");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Linha 1");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Linha 2");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setText("Linha 3");

        txtLinha5.setBackground(new java.awt.Color(0, 0, 0));
        txtLinha5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLinha5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtLinha6.setBackground(new java.awt.Color(51, 255, 51));
        txtLinha6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtLinha6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Mapeamento da Cache", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnCacheDireto.setText(" Direto");
        btnCacheDireto.setEnabled(false);
        btnCacheDireto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacheDiretoActionPerformed(evt);
            }
        });

        btnCacheAssociativo.setText("Associativo");
        btnCacheAssociativo.setEnabled(false);
        btnCacheAssociativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacheAssociativoActionPerformed(evt);
            }
        });

        btnCacheConjuntos.setText("Associativo por Conjuntos");
        btnCacheConjuntos.setEnabled(false);
        btnCacheConjuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacheConjuntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCacheDireto)
                    .addComponent(btnCacheAssociativo)
                    .addComponent(btnCacheConjuntos))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCacheDireto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCacheAssociativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCacheConjuntos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLinha1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(txtLinha2)
                            .addComponent(txtLinha3)
                            .addComponent(txtLinha4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLinha5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinha6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(txtLinha6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(txtLinha5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Processador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("PC:");

        jLabel2.setText("IR:");

        jLabel3.setText("MAR:");

        jLabel4.setText("MBR:");

        painel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registradores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setText("A:");

        jLabel6.setText("B:");

        jLabel7.setText("C:");

        jLabel8.setText("D:");

        txtRegA.setEditable(false);
        txtRegA.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtRegA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRegB.setEditable(false);
        txtRegB.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtRegB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRegC.setEditable(false);
        txtRegC.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtRegC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRegD.setEditable(false);
        txtRegD.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtRegD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout painel4Layout = new javax.swing.GroupLayout(painel4);
        painel4.setLayout(painel4Layout);
        painel4Layout.setHorizontalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegA, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegD))
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegB))
                    .addGroup(painel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegC)))
                .addContainerGap())
        );
        painel4Layout.setVerticalGroup(
            painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRegA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRegB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRegC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRegD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        txtPC.setEditable(false);
        txtPC.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtPC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtIR.setEditable(false);
        txtIR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtIR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtMAR.setEditable(false);
        txtMAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtMAR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtMBR.setEditable(false);
        txtMBR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        txtMBR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout painel3Layout = new javax.swing.GroupLayout(painel3);
        painel3.setLayout(painel3Layout);
        painel3Layout.setHorizontalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIR))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPC))
                    .addComponent(painel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel3Layout.createSequentialGroup()
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMAR)
                            .addComponent(txtMBR))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel3Layout.setVerticalGroup(
            painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrada de Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        painel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Operandos"));

        jLabel9.setText("Selecione Operandos e a operação:");

        txtOperando1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtOperando2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbOperacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/" }));

        btnConfirmar.setText("Confirmar ");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel6Layout = new javax.swing.GroupLayout(painel6);
        painel6.setLayout(painel6Layout);
        painel6Layout.setHorizontalGroup(
            painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel6Layout.createSequentialGroup()
                        .addComponent(txtOperando1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOperando2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel6Layout.createSequentialGroup()
                        .addGroup(painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(btnConfirmar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painel6Layout.setVerticalGroup(
            painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperando1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperando2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instruções assembly", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        taPalavras.setEditable(false);
        taPalavras.setColumns(20);
        taPalavras.setRows(5);
        jScrollPane3.setViewportView(taPalavras);

        btnEnviarDados.setText("Enviar Dados");
        btnEnviarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEnviarDados)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarDados)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painel5Layout = new javax.swing.GroupLayout(painel5);
        painel5.setLayout(painel5Layout);
        painel5Layout.setHorizontalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painel5Layout.setVerticalGroup(
            painel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBusca.setText("Busca ");
        btnBusca.setEnabled(false);
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnDecodifica.setText("Decodifica");
        btnDecodifica.setEnabled(false);
        btnDecodifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecodificaActionPerformed(evt);
            }
        });

        btnExecuta.setText("Executa");
        btnExecuta.setEnabled(false);
        btnExecuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutaActionPerformed(evt);
            }
        });

        painel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela Saida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        taTelaSaida.setEditable(false);
        taTelaSaida.setColumns(20);
        taTelaSaida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        taTelaSaida.setRows(5);
        jScrollPane5.setViewportView(taTelaSaida);

        javax.swing.GroupLayout painel7Layout = new javax.swing.GroupLayout(painel7);
        painel7.setLayout(painel7Layout);
        painel7Layout.setHorizontalGroup(
            painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        painel7Layout.setVerticalGroup(
            painel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        btnRestart.setBackground(new java.awt.Color(0, 0, 0));
        btnRestart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRestart.setForeground(new java.awt.Color(0, 255, 0));
        btnRestart.setText("ON/OFF");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca)
                    .addComponent(btnDecodifica)
                    .addComponent(btnExecuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRestart)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(painel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(painel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecodifica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExecuta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(painel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            int operando1 = Integer.valueOf(txtOperando1.getText());
            int operando2 = Integer.valueOf(txtOperando2.getText());

            String operacao = (String) cbOperacao.getSelectedItem();
            //System.out.println(operacao);

            String codigo1 = "";
            String codigo2 = "";
            String codigo3 = "";

            switch (operacao) {
                case "+": {
                    codigo1 = "MOV A, " + operando1;
                    codigo2 = "MOV B, " + operando2;
                    codigo3 = "ADD A, B";
                    
                }
                break;
                case "-": {
                    codigo1 = "MOV A, " + operando1;
                    codigo2 = "MOV B, " + operando2;
                    codigo3 = "SUB A, B";
                }
                break;
                case "*": {
                    codigo1 = "MOV A, " + operando1;
                    codigo2 = "MOV B, " + operando2;
                    codigo3 = "MUL A, B";
                }
                break;
                case "/": {
                    codigo1 = "MOV A, " + operando1;
                    codigo2 = "MOV B, " + operando2;
                    codigo3 = "DIV A, B";
                }
                break;
            }

            taPalavras.append(codigo1 + "\n");
            taPalavras.append(codigo2 + "\n");
            taPalavras.append(codigo3 + "\n");
            taPalavras.append("OUT S, A" + "\n");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Operando inválido para a operação!");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnEnviarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarDadosActionPerformed
        taPalavras.append("NOP A, 0" + "\n");
        vetorInstrucoes = taPalavras.getText().split("\n");
        String[] enderecos = {"0x0000","0x0001","0x0002",
                              "0x0100","0x0101","0x0102",
                              "0x0200","0x0201","0x0202",
                              "0x0300","0x0301","0x0302",
                              "0x0400","0x0401","0x0402",
                              "0x0500","0x0501","0x0502",
                              "0x0600","0x0601","0x0602",
                              "0x0700","0x0701","0x0702"};
        
        if(vetorInstrucoes.length <=24){
            for (int i = 0; i < vetorInstrucoes.length; i++) {
                System.out.println(vetorInstrucoes[i]);
                    pc.getEnderecosMemoriaPrincipal().put(enderecos[i], vetorInstrucoes[i]);
            }
            
            listMemoriaPrincipal.setListData(vetorInstrucoes);
            listMemoriaPrincipalEnderecos.setListData(pc.getMemoriaPrincipal().getEnderecos().keySet().toArray());
            btnBusca.setEnabled(true);
            btnDecodifica.setEnabled(false);
            btnExecuta.setEnabled(false);
            btnCacheDireto.setEnabled(false);
            btnCacheAssociativo.setEnabled(true);
            btnCacheConjuntos.setEnabled(true);
            taPalavras.setText("");
            txtLinha1.setText("");
            txtLinha2.setText("");
            txtLinha3.setText("");
            txtLinha4.setText("");
            pc.getProcessador().restart();
            atualizaRegistradores();
            MemoriaCache cache = new MemoriaCache(pc.getMemoriaPrincipal());
            pc.setMemoriaCache(cache);
        }else{
            JOptionPane.showMessageDialog(null, "Número de instruções maior que a quantidade de endereços da Memória Principal!");
            taPalavras.setText("");
        }

    }//GEN-LAST:event_btnEnviarDadosActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        if(!btnCacheDireto.isEnabled()){
            pc.getProcessador().buscaInstrucao(pc.getMemoriaCache(),pc.getMemoriaPrincipal(), pc.getProcessador().getPC());
            
        }else if(!btnCacheAssociativo.isEnabled()){
            pc.getProcessador().buscaInstrucaoAssociativo(pc.getMemoriaCache(),pc.getMemoriaPrincipal(), pc.getProcessador().getPC());
            
        }else if(!btnCacheConjuntos.isEnabled()){
            pc.getProcessador().buscaInstrucaoAssociativoPorConjuntos(pc.getMemoriaCache(), pc.getMemoriaPrincipal(), pc.getProcessador().getPC());
        }
        
        atualizaRegistradores();
        btnBusca.setEnabled(false);
        btnDecodifica.setEnabled(true);
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnDecodificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecodificaActionPerformed
        pc.getProcessador().decodificaInstrucao(pc.getProcessador().getIR());
        atualizaRegistradores();
        btnDecodifica.setEnabled(false);
        btnExecuta.setEnabled(true);
    }//GEN-LAST:event_btnDecodificaActionPerformed

    private void btnExecutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutaActionPerformed
        pc.getProcessador().executaInstrucao();
        atualizaRegistradores();
        btnBusca.setEnabled(true);
        btnDecodifica.setEnabled(false);
        btnExecuta.setEnabled(false);
    }//GEN-LAST:event_btnExecutaActionPerformed

    private void btnCacheDiretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacheDiretoActionPerformed
        btnCacheDireto.setEnabled(false);
        btnCacheAssociativo.setEnabled(true);
        btnCacheConjuntos.setEnabled(true);
        
    }//GEN-LAST:event_btnCacheDiretoActionPerformed

    private void btnCacheAssociativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacheAssociativoActionPerformed
        btnCacheDireto.setEnabled(true);
        btnCacheAssociativo.setEnabled(false);
        btnCacheConjuntos.setEnabled(true);
        
    }//GEN-LAST:event_btnCacheAssociativoActionPerformed

    private void btnCacheConjuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacheConjuntosActionPerformed
        btnCacheDireto.setEnabled(true);
        btnCacheAssociativo.setEnabled(true);
        btnCacheConjuntos.setEnabled(false);
        
    }//GEN-LAST:event_btnCacheConjuntosActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        TelaPrincipal telaNova = new TelaPrincipal();
        telaNova.setLocationRelativeTo(null);
        telaNova.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCacheAssociativo;
    private javax.swing.JButton btnCacheConjuntos;
    private javax.swing.JButton btnCacheDireto;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnDecodifica;
    private javax.swing.JButton btnEnviarDados;
    private javax.swing.JButton btnExecuta;
    private javax.swing.JButton btnRestart;
    private javax.swing.JComboBox cbOperacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList listMemoriaPrincipal;
    private javax.swing.JList listMemoriaPrincipalEnderecos;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painel2;
    private javax.swing.JPanel painel3;
    private javax.swing.JPanel painel4;
    private javax.swing.JPanel painel5;
    private javax.swing.JPanel painel6;
    private javax.swing.JPanel painel7;
    private javax.swing.JTextArea taPalavras;
    private javax.swing.JTextArea taTelaSaida;
    private javax.swing.JTextField txtIR;
    private javax.swing.JTextField txtLinha1;
    private javax.swing.JTextField txtLinha2;
    private javax.swing.JTextField txtLinha3;
    private javax.swing.JTextField txtLinha4;
    private javax.swing.JTextField txtLinha5;
    private javax.swing.JTextField txtLinha6;
    private javax.swing.JTextField txtMAR;
    private javax.swing.JTextField txtMBR;
    private javax.swing.JTextField txtOperando1;
    private javax.swing.JTextField txtOperando2;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtRegA;
    private javax.swing.JTextField txtRegB;
    private javax.swing.JTextField txtRegC;
    private javax.swing.JTextField txtRegD;
    // End of variables declaration//GEN-END:variables
}
